services:
  db:
    image: postgres:17
    container_name: db-docker
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: web-docker
    depends_on:
      - db
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx-docker
    ports:
      - "8001:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
      - ./media:/media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
volumes:
  postgres_data:
