"""
Django settings for kennel project.

Generated by 'django-admin startproject' using Django 5.0.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%$xpffwek!b0direk)=vlx^@uk(nz!elj0s0t5!6m*k*%zygpi"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # my app
    "apps.users",
    "apps.dogs",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "kennel.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kennel.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

load_dotenv()

USER = os.getenv("MS_SQL_USER")
PASSWORD = os.getenv("MS_SQL_KYE")
HOST = os.getenv("MS_SQL_SERVER")
DATABASE = os.getenv("MS_SQL_DATABASE")
PAD_DATABASE = os.getenv("MS_PAD_DATABASE")
DRIVER = os.getenv("MS_SQL_DRIVER")

DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": DATABASE,
        "PASSWORD": PASSWORD,
        "HOST": HOST,
        "PORT": "",
        "OPTIONS": {"driver": DRIVER},
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "users.User"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s - %(levelname)s - %(name)s - %(message)s",
        },
        "simple": {
            "format": "%(levelname)s - %(name)s - %(message)s",
        },
        "error": {
            "format": "%(asctime)s - %(levelname)s - %(name)s - %(lineno)d - %(message)s",
        },
    },
    "handlers": {
        # Обработчик для записи логов в файл
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs/info-file.log",
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        # Обработчик для вывода логов в консоль
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        # Отдельный обработчик ERROR для записи подробных логов в файл
        "error_file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs/error-file.log",
            "formatter": "error",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        # logger для django
        "django": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        # logger для ошибок в django
        "django.errors": {
            "handlers": ["error_file"],
            "level": "ERROR",
            "propagate": False,
        },
        # logger для приложения users
        "users": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        # logger для ошибок в users
        "users.errors": {
            "handlers": ["error_file"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
