# Generated by Django 5.0.13 on 2025-03-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Пользователь"),
                    ("moderator", "Модератор"),
                    ("admin", "Администратор"),
                ],
                default="user",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram",
            field=models.CharField(blank=True, max_length=50, verbose_name="Телеграм"),
        ),
    ]
