# Generated by Django 5.0.13 on 2025-03-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_role_alter_user_first_name_alter_user_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
