# Generated by Django 5.0.13 on 2025-03-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("М", "Мужской"), ("Ж", "Женский")],
                max_length=1,
                null=True,
                verbose_name="Пол",
            ),
        ),
    ]
