# Generated by Django 5.0.13 on 2025-03-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="breed",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="breed/", verbose_name="Фото"
            ),
        ),
    ]
